baseURL = "https://stefan-birkner.de/"
disableHugoGeneratorInject = true
disableKinds = ["RSS", "sitemap", "taxonomy", "term"]
disablePathToLower = true
languageCode = "en-us"
title = "Stefan Birkner's Website"


[markup.goldmark.renderer]
unsafe= true