<?php
$l1 = "Ett fel har uppst&aring;tt";
$l2 = "&lt;&lt;&lt; Tillbaka";
$l3 = "Programmet kunde inte ansluta till POP-servern. H&auml;r &auml;r felmeddelandet:";
$l4 = "Programmet kunde inte logga in p&aring; POP-servern. Trolig orsak &auml;r fel anv&auml;ndarnamn, l&ouml;senord eller port.";
$l5 = "OK";
$l6 = "Logga in med dina uppgifter";
$l7 = "L&ouml;senord:";
$l8 = "Anv&auml;ndarnamn:";
$l9 = "POP-serverns port:";
$l10 = "POP-serverns adress:";
$l11 = "Det finns inga brev i inkorgen.";
$l12 = "Programmet kunde inte k&ouml;ra kommandot TOP.";
$l13 = "[Inget &auml;mne]";
$l15 = "Programmet kunde inte h&auml;mta e-postbrevet nr. $id.";
$l16 = "Fr&aring;n:";
$l17 = "Till:";
$l18 = "Datum:";
$l19 = "Organisation:";
$l20 = "E-postklient:";
$l21 = "Svara till:";
$l22 = "Brevhuvud";
$l23 = "Kopia:";
$l24 = "Svara";
$l25 = "Vidarebefodra";
$l26 = "Radera";
$l27 = "Svara alla";
$l28 = "Skriv ut";
$l29 = "Visa k&auml;lla";
$l30 = "Spr&aring;k:";
$l31 = "Är du säker på att du vill radera detta brevet?";
$l32 = "Meddelande nr. $id kunde inte raderas.";
$l33 = "Skicka nytt brev";
$l34 = "Uppdatera";
$l35 = "[Ok&auml;nt filnamn]";
$l36 = "&auml;mne:";
$l37 = "Fr&aring;n:";
$l38 = "Till:";
$l39 = "Kopia till:";
$l40 = "Dold kopia till:";
$l41 = "Bifoga fil:";
$l42 = "Skicka som HTML";
$l43 = "Skicka";
$l44 = "Skicka brevet direkt?";
# Do not translate [date] and [sender]. Think of them as variables. The
# string will be transformed into e.g. "On 08-08-2001 12:42, John Doe
# <doe@example.com> wrote":$l45 = "Den [date], skrev [sender]:";
$l45 = "Den [date], skrev [sender]:";
$l46 = "Vidarebefodra brevet";
$l47 = "ni";
$l48 = "Glöm inte att ange en giltig e-postadress.";
$l49 = "Glöm inte att ange en giltig mottagare.";
# The character set corresponding to your language:
$l50 = "ISO-8859-1";
$l51 = "Programmet kunde inte l&auml;sa en av de bifogade filerna. Antagligen &auml;r det fel r&auml;ttigheter p&aring; mappen f&ouml;r dessa filer. Var v&auml;nlig kontakta administrat&ouml;ren.";
$l52 = "Logga ut";
$l53 = "Licens: <a href='license.txt' target='_blank'>GNU General Public License</a>";
$l54 = "Om programmet";
$l55 = "F&ouml;rinst&auml;lld POP-server:";
$l56 = "F&ouml;rinst&auml;lld POP-serverport:";
$l57 = "F&ouml;rinst&auml;llt POP-anv&auml;ndarnamn:";
$l58 = "Uppdelning av ramar";
$l59 = "Vertikal";
$l60 = "Horisontal";
$l61 = "Inst&auml;llning";
$l62 = "Spara inst&auml;llningarna";
$l63 = "Huvudmeny i procent:";
$l64 = "Meddelanderamen i procent:";
$l65 = "Sidfot (alla sidor):";
$l66 = "Huvud till inloggningssidan:";
$l67 = "Sidfot till inloggningssidan:";
$l68 = "Titeln i webbl&auml;sarens titelrad:";
$l69 = "Programmet har inte r&auml;ttigheter att skriva till filen settingssaved.php. Denna filen m&aring;ste ha CHMOD 666.";
$l70 = "Inst&auml;llningarna &auml;r sparade.";
$l71 = "Beh&aring;ll l&ouml;senordet";
$l72 = "Nytt l&ouml;senord:";
$l73 = "L&ouml;senord f&ouml;r administrationssidan:";
$l74 = "Anv&auml;ndarnamn f&ouml;r administrationssidan:";
$l75 = "&aring;tkomst nekad.";
$l76 = "Autouppdatering: %s";
$l77 = "p&aring;";
$l78 = "av";
$l79 = "Antal minuter mellan varje kontroll:";
$l80 = "Är du säker på att du vill logga ut?";
$l81 = "Tema:";
$l82 = "<a href='readme.html' target='_blank'>Visa L&auml;sMig-filen</a>";
$l83 = "Formatering av texten:";
$l84 = "Ja";
$l85 = "Nej";
$l86 = "Beg&auml;r bekr&auml;ftelse";
$l87 = "Prioritet:";
$l88 = "H&ouml;g";
$l89 = "Normal";
$l90 = "L&aring;g";
$l91 = "H&ouml;gsta";
$l92 = "L&auml;gsta";
$l93 = "Formaterad text Av eller P&aring;. Om du valt P&aring;, vanliga textmeddelanden blir formaterade s&aring; att *fetstil* blir konverterad till <b>fetstil</b>, /kursiv/ konverteras till <i>kursiv</i>, och _understruken_ till <u>understruken</u>.";
$l94 = "Hj&auml;lp";
$l95 = "St&auml;ng";
$l96 = "Om du vill begr&auml;nsa antalet POP-servrar till endast en eller n&aring;gra f&aring; f&ouml;rdefinerade POP-servrar, skriv en lista p&aring; dessa servrar separerade med ett komma och blanksteg. Exempel: <i>post1.doman.se, post2.doman.se, post3.doman.se</i>.";
$l97 = "Skriv ett eller flera portnummer separerade med komma och blanksteg. Exempel: <i>110, 111</i>.";
$l98 = "Skriv en eller flera anv&auml;ndare separerade med komma och blanksteg, Exempel: <i>anv&auml;ndare1, anv&auml;ndare2</i>.";
$l99 = "Epostadress:";
$l100 = "Du har inte markerat vilket/vilka brev som ska raderas.";
$l101 = "Är du säker att du vill radera markerade brev?";
$l102 = "(Av)Markera alla";
$l103 = "L&ouml;senordet igen:";
$l104 = "De b&aring;da l&ouml;senorden &ouml;verenst&auml;mmer inte.";



function l14($timeStamp) {
	return date("Y-m-d H:i", $timeStamp);
}
?>